---
engines:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  golint:
    enabled: true
    exclude_fingerprints:
    - 62ce3db3d98c7d7f6ce571bbde9d6491
    - 26264ff7d8ba94d468dfa7170baa8e03
  gofmt:
    enabled: true
  govet:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths: []
